In [ ]:
from os import link
import pandas as pd
data = pd.read_csv('data_road.csv')

In [ ]:
length = len(data)

In [ ]:
import pandas as pd

news_data = pd.DataFrame(columns=['news_raw'])

for l in range(length-1):
    news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)

<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)
<ipython-input-5-bd2349ad4807>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  news_data = news_data.append({'news_raw': data['content'][l]}, ignore_index=True)

In [ ]:
news_data.shape

(38, 1)

In [ ]:
news_data

                                             news_raw
0   Trichy : A 15-year-old boy was killed after he...
1   HISAR: Three men were killed and three others ...
2   New Delhi: A two-and-a-half-year-old boy was c...
3   AHMEDABAD: No city in Gujarat is immune from s...
4   Kota: Two people were killed and three others ...
5   NEW DELHI: Three individuals, including an inf...
6   JALANDHAR: At least four people were killed, a...
7   BILASPUR : One person was killed and three oth...
8   MUMBAI: Two men died and four others were inju...
9   The former Mayor of Chennai, Saidai Duraisamy'...
10  Kochi: Two people were killed in separate road...
11  In a swift turn of events, rumors circulating ...
12  New Delhi: Two weeks after a car collided with...
13  BHUBANESWAR: Four people were killed in a car ...
14  JAMMU : Four members of a family were killed a...
15  Jabalpur : Two siblings who had gone for a mor...
16  VIRUDHUNAGAR: An elderly man riding on a bicyc...
17  BHUBANESWAR: Three men died and noted Ollywood...
18  NEW DELHI: While driving his Mercedes SUV from...
19  Kallakurichi: A Chennai police constable and h...
20  Visakhapatnam: Five persons, including two chi...
21  Ghaziabad: A 16-year-old boy was killed after ...
22  NELLORE: One person was killed, and two others...
23  NEW DELHI: A car tumbled into the Sutlej River...
24  AHMEDNAGAR: Six individuals lost their lives a...
25  Renowned Punjabi singer and actor Sippy Gill r...
26  Nagpur: Two persons, including a round officer...
27  Jalandhar: Three persons were killed in a road...
28  South Korean actor Ji Gun-woo of ' Alienoid ' ...
29  Singer Zayn Malik met with a minor accident wh...
30  NEW DELHI: At least six people were killed whi...
31  NEW DELHI: Two Delhi Police inspectors were ki...
32  New Delhi: A 40-year-old businessman died and ...
33  RANCHI: Four youths lost their lives when thei...
34  Jung Il Woo recently opened up about a pivotal...
35  PATNA: Ranjit Sah does not know the nuances of...
36  Hyderabad: A 28-year-old software engineer , w...
37  NEW DELHI: A 20-year-old woman was killed and ...

# Tokenize

In [ ]:
import re
def tokenize(text):
  tokens = re.split('\W+',text)
  return tokens
news_data['news_tokenized'] = news_data['news_raw'].apply(lambda x: tokenize(x.lower()))

In [ ]:
news_data

,news_raw,news_tokenized
0,Trichy : A 15-year-old boy was killed after he...,"[trichy, a, 15, year, old, boy, was, killed, a..."
1,HISAR: Three men were killed and three others ...,"[hisar, three, men, were, killed, and, three, ..."
2,New Delhi: A two-and-a-half-year-old boy was c...,"[new, delhi, a, two, and, a, half, year, old, ..."
3,AHMEDABAD: No city in Gujarat is immune from s...,"[ahmedabad, no, city, in, gujarat, is, immune,..."
4,Kota: Two people were killed and three others ...,"[kota, two, people, were, killed, and, three, ..."
5,"NEW DELHI: Three individuals, including an inf...","[new, delhi, three, individuals, including, an..."
6,"JALANDHAR: At least four people were killed, a...","[jalandhar, at, least, four, people, were, kil..."
7,BILASPUR : One person was killed and three oth...,"[bilaspur, one, person, was, killed, and, thre..."
8,MUMBAI: Two men died and four others were inju...,"[mumbai, two, men, died, and, four, others, we..."
9,"The former Mayor of Chennai, Saidai Duraisamy'...","[the, former, mayor, of, chennai, saidai, dura..."
10,Kochi: Two people were killed in separate road...,"[kochi, two, people, were, killed, in, separat..."
11,"In a swift turn of events, rumors circulating ...","[in, a, swift, turn, of, events, rumors, circu..."
12,New Delhi: Two weeks after a car collided with...,"[new, delhi, two, weeks, after, a, car, collid..."
13,BHUBANESWAR: Four people were killed in a car ...,"[bhubaneswar, four, people, were, killed, in, ..."
14,JAMMU : Four members of a family were killed a...,"[jammu, four, members, of, a, family, were, ki..."
15,Jabalpur : Two siblings who had gone for a mor...,"[jabalpur, two, siblings, who, had, gone, for,..."
16,VIRUDHUNAGAR: An elderly man riding on a bicyc...,"[virudhunagar, an, elderly, man, riding, on, a..."
17,BHUBANESWAR: Three men died and noted Ollywood...,"[bhubaneswar, three, men, died, and, noted, ol..."
18,NEW DELHI: While driving his Mercedes SUV from...,"[new, delhi, while, driving, his, mercedes, su..."
19,Kallakurichi: A Chennai police constable and h...,"[kallakurichi, a, chennai, police, constable, ..."
20,"Visakhapatnam: Five persons, including two chi...","[visakhapatnam, five, persons, including, two,..."
21,Ghaziabad: A 16-year-old boy was killed after ...,"[ghaziabad, a, 16, year, old, boy, was, killed..."
22,"NELLORE: One person was killed, and two others...","[nellore, one, person, was, killed, and, two, ..."
23,NEW DELHI: A car tumbled into the Sutlej River...,"[new, delhi, a, car, tumbled, into, the, sutle..."
24,AHMEDNAGAR: Six individuals lost their lives a...,"[ahmednagar, six, individuals, lost, their, li..."
25,Renowned Punjabi singer and actor Sippy Gill r...,"[renowned, punjabi, singer, and, actor, sippy,..."
26,"Nagpur: Two persons, including a round officer...","[nagpur, two, persons, including, a, round, of..."
27,Jalandhar: Three persons were killed in a road...,"[jalandhar, three, persons, were, killed, in, ..."
28,South Korean actor Ji Gun-woo of ' Alienoid ' ...,"[south, korean, actor, ji, gun, woo, of, alien..."
29,Singer Zayn Malik met with a minor accident wh...,"[singer, zayn, malik, met, with, a, minor, acc..."
30,NEW DELHI: At least six people were killed whi...,"[new, delhi, at, least, six, people, were, kil..."
31,NEW DELHI: Two Delhi Police inspectors were ki...,"[new, delhi, two, delhi, police, inspectors, w..."
32,New Delhi: A 40-year-old businessman died and ...,"[new, delhi, a, 40, year, old, businessman, di..."
33,RANCHI: Four youths lost their lives when thei...,"[ranchi, four, youths, lost, their, lives, whe..."
34,Jung Il Woo recently opened up about a pivotal...,"[jung, il, woo, recently, opened, up, about, a..."
35,PATNA: Ranjit Sah does not know the nuances of...,"[patna, ranjit, sah, does, not, know, the, nua..."
36,"Hyderabad: A 28-year-old software engineer , w...","[hyderabad, a, 28, year, old, software, engine..."
37,NEW DELHI: A 20-year-old woman was killed and ...,"[new, delhi, a, 20, year, old, woman, was, kil..."

# Remove Stopwords

In [ ]:
import nltk
nltk.download('stopwords')

stopwords = nltk.corpus.stopwords.words('english')

def remove_stopwords(news_tokenized):
  text = [word for word in news_tokenized if word not in stopwords]
  return text

news_data['news_nostop'] = news_data['news_tokenized'].apply(lambda x: remove_stopwords(x))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
news_data['news_nostop']

,news_raw,news_tokenized,news_nostop
0,Trichy : A 15-year-old boy was killed after he...,"[trichy, a, 15, year, old, boy, was, killed, a...","[trichy, 15, year, old, boy, killed, hit, unid..."
1,HISAR: Three men were killed and three others ...,"[hisar, three, men, were, killed, and, three, ...","[hisar, three, men, killed, three, others, inj..."
2,New Delhi: A two-and-a-half-year-old boy was c...,"[new, delhi, a, two, and, a, half, year, old, ...","[new, delhi, two, half, year, old, boy, crushe..."
3,AHMEDABAD: No city in Gujarat is immune from s...,"[ahmedabad, no, city, in, gujarat, is, immune,...","[ahmedabad, city, gujarat, immune, stray, dog,..."
4,Kota: Two people were killed and three others ...,"[kota, two, people, were, killed, and, three, ...","[kota, two, people, killed, three, others, cri..."
5,"NEW DELHI: Three individuals, including an inf...","[new, delhi, three, individuals, including, an...","[new, delhi, three, individuals, including, in..."
6,"JALANDHAR: At least four people were killed, a...","[jalandhar, at, least, four, people, were, kil...","[jalandhar, least, four, people, killed, two, ..."
7,BILASPUR : One person was killed and three oth...,"[bilaspur, one, person, was, killed, and, thre...","[bilaspur, one, person, killed, three, others,..."
8,MUMBAI: Two men died and four others were inju...,"[mumbai, two, men, died, and, four, others, we...","[mumbai, two, men, died, four, others, injured..."
9,"The former Mayor of Chennai, Saidai Duraisamy'...","[the, former, mayor, of, chennai, saidai, dura...","[former, mayor, chennai, saidai, duraisamy, so..."
10,Kochi: Two people were killed in separate road...,"[kochi, two, people, were, killed, in, separat...","[kochi, two, people, killed, separate, road, a..."
11,"In a swift turn of events, rumors circulating ...","[in, a, swift, turn, of, events, rumors, circu...","[swift, turn, events, rumors, circulating, soc..."
12,New Delhi: Two weeks after a car collided with...,"[new, delhi, two, weeks, after, a, car, collid...","[new, delhi, two, weeks, car, collided, auto, ..."
13,BHUBANESWAR: Four people were killed in a car ...,"[bhubaneswar, four, people, were, killed, in, ...","[bhubaneswar, four, people, killed, car, accid..."
14,JAMMU : Four members of a family were killed a...,"[jammu, four, members, of, a, family, were, ki...","[jammu, four, members, family, killed, one, cr..."
15,Jabalpur : Two siblings who had gone for a mor...,"[jabalpur, two, siblings, who, had, gone, for,...","[jabalpur, two, siblings, gone, morning, walk,..."
16,VIRUDHUNAGAR: An elderly man riding on a bicyc...,"[virudhunagar, an, elderly, man, riding, on, a...","[virudhunagar, elderly, man, riding, bicycle, ..."
17,BHUBANESWAR: Three men died and noted Ollywood...,"[bhubaneswar, three, men, died, and, noted, ol...","[bhubaneswar, three, men, died, noted, ollywoo..."
18,NEW DELHI: While driving his Mercedes SUV from...,"[new, delhi, while, driving, his, mercedes, su...","[new, delhi, driving, mercedes, suv, new, delh..."
19,Kallakurichi: A Chennai police constable and h...,"[kallakurichi, a, chennai, police, constable, ...","[kallakurichi, chennai, police, constable, wif..."
20,"Visakhapatnam: Five persons, including two chi...","[visakhapatnam, five, persons, including, two,...","[visakhapatnam, five, persons, including, two,..."
21,Ghaziabad: A 16-year-old boy was killed after ...,"[ghaziabad, a, 16, year, old, boy, was, killed...","[ghaziabad, 16, year, old, boy, killed, bike, ..."
22,"NELLORE: One person was killed, and two others...","[nellore, one, person, was, killed, and, two, ...","[nellore, one, person, killed, two, others, in..."
23,NEW DELHI: A car tumbled into the Sutlej River...,"[new, delhi, a, car, tumbled, into, the, sutle...","[new, delhi, car, tumbled, sutlej, river, utta..."
24,AHMEDNAGAR: Six individuals lost their lives a...,"[ahmednagar, six, individuals, lost, their, li...","[ahmednagar, six, individuals, lost, lives, st..."
25,Renowned Punjabi singer and actor Sippy Gill r...,"[renowned, punjabi, singer, and, actor, sippy,...","[renowned, punjabi, singer, actor, sippy, gill..."
26,"Nagpur: Two persons, including a round officer...","[nagpur, two, persons, including, a, round, of...","[nagpur, two, persons, including, round, offic..."
27,Jalandhar: Three persons were killed in a road...,"[jalandhar, three, persons, were, killed, in, ...","[jalandhar, three, persons, killed, road, acci..."
28,South Korean actor Ji Gun-woo of ' Alienoid ' ...,"[south, korean, actor, ji, gun, woo, of, alien...","[south, korean, actor, ji, gun, woo, alienoid,..."
29,Singer Zayn Malik met with a minor accident wh...,"[singer, zayn, malik, met, with, a, minor, acc...","[singer, zayn, malik, met, minor, accident, ma..."
30,NEW DELHI: At least six people were killed whi...,"[new, delhi, at, least, six, people, were, kil...","[new, delhi, least, six, people, killed, two, ..."
31,NEW DELHI: Two Delhi Police inspectors were ki...,"[new, delhi, two, delhi, police, inspectors, w...","[new, delhi, two, delhi, police, inspectors, k..."
32,New Delhi: A 40-year-old businessman died and ...,"[new, delhi, a, 40, year, old, businessman, di...","[new, delhi, 40, year, old, businessman, died,..."
33,RANCHI: Four youths lost their lives when thei...,"[ranchi, four, youths, lost, their, lives, whe...","[ranchi, four, youths, lost, lives, car, colli..."
34,Jung Il Woo recently opened up about a pivotal...,"[jung, il, woo, recently, opened, up, about, a...","[jung, il, woo, recently, opened, pivotal, mom..."
35,PATNA: Ranjit Sah does not know the nuances of...,"[patna, ranjit, sah, does, not, know, the, nua...","[patna, ranjit, sah, know, nuances, law, provi..."
36,"Hyderabad: A 28-year-old software engineer , w...","[hyderabad, a, 28, year, old, software, engine...","[hyderabad, 28, year, old, software, engineer,..."
37,NEW DELHI: A 20-year-old woman was killed and ...,"[new, delhi, a, 20, year, old, woman, was, kil...","[new, delhi, 20, year, old, woman, killed, 62,..."

# Vectorize using TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer()
x_tfidf = tfidf_vect.fit_transform(news_data['news_raw'])
x_tfidf

<38x2051 sparse matrix of type '<class 'numpy.float64'>'
	with 4849 stored elements in Compressed Sparse Row format>

In [ ]:
tfidf_df = pd.DataFrame(x_tfidf.toarray(), columns=tfidf_vect.get_feature_names_out())
tfidf_df.to_csv('TF_IDF')

# Using word2vec

In [ ]:
!pip install -U gensim

Requirement already satisfied: gensim in /usr/local/lib/python3.10/dist-packages (4.3.2)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.10/dist-packages (from gensim) (1.25.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from gensim) (1.11.4)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.10/dist-packages (from gensim) (6.4.0)

In [ ]:
import gensim.downloader as api

wiki_embeddings = api.load('word2vec-google-news-300  ')

[==================================================] 100.0% 1662.8/1662.8MB downloaded

# spaCy

In [ ]:
import spacy
from spacy import displacy

In [ ]:
ner_pipeline = spacy.load("en_core_web_sm")

In [ ]:
ner_pipeline_labels = ner_pipeline.get_pipe("ner").labels
ner_pipeline_labels

('CARDINAL',
 'DATE',
 'EVENT',
 'FAC',
 'GPE',
 'LANGUAGE',
 'LAW',
 'LOC',
 'MONEY',
 'NORP',
 'ORDINAL',
 'ORG',
 'PERCENT',
 'PERSON',
 'PRODUCT',
 'QUANTITY',
 'TIME',
 'WORK_OF_ART')

In [ ]:
spacy.explain("WORK_OF_ART")

'Titles of books, songs, etc.'

In [ ]:
news_str = str(news_data['news_raw'][1])

In [ ]:
ner_text = ner_pipeline(news_str)

In [ ]:
for word in ner_text.ents:
    print(word.text,word.label_,word.start_char, word.end_char)

Three CARDINAL 7 12
three CARDINAL 33 38
Hisar ORG 95 100
Hisar ORG 160 165
Bhiwani GPE 204 211
Thursday DATE 224 232
night TIME 233 238
Harikot NORP 333 340
Haryana ORG 416 423
Dakshin Haryana Bijli Vitran Nigam PERSON 439 473
Bhuvnesh Sangwan PERSON 536 552
Rewari ORG 558 564
Mandeep Kundu PERSON 566 579
Hisar ORG 585 590
Fatehabad GPE 608 617
Hisar ORG 679 684

In [ ]:
displacy.render(ner_text,style="ent",jupyter=True)

In [ ]:
%%capture
!pip install spacy-annotator

In [ ]:
import spacy_annotator as spa
from pprint import pprint

In [ ]:
annotator = spa.Annotator(labels=['place','age','vehicle','time'],model=ner_pipeline)

In [ ]:
news_labels = annotator.annotate(df=news_data,col_text='news_raw')

HTML(value='-1 examples annotated, 39 examples left')

Text(value='', description='place', layout=Layout(width='auto'), placeholder='ent one, ent two, ent three')

Text(value='', description='age', layout=Layout(width='auto'), placeholder='ent one, ent two, ent three')

Text(value='', description='vehicle', layout=Layout(width='auto'), placeholder='ent one, ent two, ent three')

Text(value='', description='time', layout=Layout(width='auto'), placeholder='ent one, ent two, ent three')

HBox(children=(Button(button_style='success', description='submit', style=ButtonStyle()), Button(button_style=…

Output()

In [ ]:
news_labels

,news_raw,news_tokenized,news_nostop,annotations
0,Trichy : A 15-year-old boy was killed after he...,"[trichy, a, 15, year, old, boy, was, killed, a...","[trichy, 15, year, old, boy, killed, hit, unid...",(Trichy : A 15-year-old boy was killed after h...
1,HISAR: Three men were killed and three others ...,"[hisar, three, men, were, killed, and, three, ...","[hisar, three, men, killed, three, others, inj...",(HISAR: Three men were killed and three others...
2,New Delhi: A two-and-a-half-year-old boy was c...,"[new, delhi, a, two, and, a, half, year, old, ...","[new, delhi, two, half, year, old, boy, crushe...",(New Delhi: A two-and-a-half-year-old boy was ...
3,AHMEDABAD: No city in Gujarat is immune from s...,"[ahmedabad, no, city, in, gujarat, is, immune,...","[ahmedabad, city, gujarat, immune, stray, dog,...",(AHMEDABAD: No city in Gujarat is immune from ...
4,Kota: Two people were killed and three others ...,"[kota, two, people, were, killed, and, three, ...","[kota, two, people, killed, three, others, cri...",(Kota: Two people were killed and three others...
5,"NEW DELHI: Three individuals, including an inf...","[new, delhi, three, individuals, including, an...","[new, delhi, three, individuals, including, in...","(NEW DELHI: Three individuals, including an in..."
6,"JALANDHAR: At least four people were killed, a...","[jalandhar, at, least, four, people, were, kil...","[jalandhar, least, four, people, killed, two, ...","(JALANDHAR: At least four people were killed, ..."
7,BILASPUR : One person was killed and three oth...,"[bilaspur, one, person, was, killed, and, thre...","[bilaspur, one, person, killed, three, others,...",(BILASPUR : One person was killed and three ot...
8,MUMBAI: Two men died and four others were inju...,"[mumbai, two, men, died, and, four, others, we...","[mumbai, two, men, died, four, others, injured...",(MUMBAI: Two men died and four others were inj...
9,"The former Mayor of Chennai, Saidai Duraisamy'...","[the, former, mayor, of, chennai, saidai, dura...","[former, mayor, chennai, saidai, duraisamy, so...","(The former Mayor of Chennai, Saidai Duraisamy..."
10,Kochi: Two people were killed in separate road...,"[kochi, two, people, were, killed, in, separat...","[kochi, two, people, killed, separate, road, a...",(Kochi: Two people were killed in separate roa...
11,"In a swift turn of events, rumors circulating ...","[in, a, swift, turn, of, events, rumors, circu...","[swift, turn, events, rumors, circulating, soc...",
12,New Delhi: Two weeks after a car collided with...,"[new, delhi, two, weeks, after, a, car, collid...","[new, delhi, two, weeks, car, collided, auto, ...",(New Delhi: Two weeks after a car collided wit...
13,BHUBANESWAR: Four people were killed in a car ...,"[bhubaneswar, four, people, were, killed, in, ...","[bhubaneswar, four, people, killed, car, accid...",(BHUBANESWAR: Four people were killed in a car...
14,JAMMU : Four members of a family were killed a...,"[jammu, four, members, of, a, family, were, ki...","[jammu, four, members, family, killed, one, cr...",(JAMMU : Four members of a family were killed ...
15,Jabalpur : Two siblings who had gone for a mor...,"[jabalpur, two, siblings, who, had, gone, for,...","[jabalpur, two, siblings, gone, morning, walk,...",(Jabalpur : Two siblings who had gone for a mo...
16,VIRUDHUNAGAR: An elderly man riding on a bicyc...,"[virudhunagar, an, elderly, man, riding, on, a...","[virudhunagar, elderly, man, riding, bicycle, ...",(VIRUDHUNAGAR: An elderly man riding on a bicy...
17,BHUBANESWAR: Three men died and noted Ollywood...,"[bhubaneswar, three, men, died, and, noted, ol...","[bhubaneswar, three, men, died, noted, ollywoo...",(BHUBANESWAR: Three men died and noted Ollywoo...
18,NEW DELHI: While driving his Mercedes SUV from...,"[new, delhi, while, driving, his, mercedes, su...","[new, delhi, driving, mercedes, suv, new, delh...",
19,Kallakurichi: A Chennai police constable and h...,"[kallakurichi, a, chennai, police, constable, ...","[kallakurichi, chennai, police, constable, wif...",(Kallakurichi: A Chennai police constable and ...
20,"Visakhapatnam: Five persons, including two chi...","[visakhapatnam, five, persons, including, two,...","[visakhapatnam, five, persons, including, two,...","(Visakhapatnam: Five persons, including two ch..."
21,Ghaziabad: A 16-year-old boy was killed after ...,"[ghaziabad, a, 16, year, old, boy, was, killed...","[ghaziabad, 16, year, old, boy, killed, bike, ...",
22,"NELLORE: One person was killed, and two others...","[nellore, one, person, was, killed, and, two, ...","[nellore, one, person, killed, two, others, in...",
23,NEW DELHI: A car tumbled into the Sutlej River...,"[new, delhi, a, car, tumbled, into, the, sutle...","[new, delhi, car, tumbled, sutlej, river, utta...",
24,AHMEDNAGAR: Six individuals lost their lives a...,"[ahmednagar, six, individuals, lost, their, li...","[ahmednagar, six, individuals, lost, lives, st...",
25,Renowned Punjabi singer and actor Sippy Gill r...,"[renowned, punjabi, singer, and, actor, sippy,...","[renowned, punjabi, singer, actor, sippy, gill...",
26,"Nagpur: Two persons, including a round officer...","[nagpur, two, persons, including, a, round, of...","[nagpur, two, persons, including, round, offic...",
27,Jalandhar: Three persons were killed in a road...,"[jalandhar, three, persons, were, killed, in, ...","[jalandhar, three, persons, killed, road, acci...",
28,South Korean actor Ji Gun-woo of ' Alienoid ' ...,"[south, korean, actor, ji, gun, woo, of, alien...","[south, korean, actor, ji, gun, woo, alienoid,...",
29,Singer Zayn Malik met with a minor accident wh...,"[singer, zayn, malik, met, with, a, minor, acc...","[singer, zayn, malik, met, minor, accident, ma...",
30,NEW DELHI: At least six people were killed whi...,"[new, delhi, at, least, six, people, were, kil...","[new, delhi, least, six, people, killed, two, ...",
31,NEW DELHI: Two Delhi Police inspectors were ki...,"[new, delhi, two, delhi, police, inspectors, w...","[new, delhi, two, delhi, police, inspectors, k...",
32,New Delhi: A 40-year-old businessman died and ...,"[new, delhi, a, 40, year, old, businessman, di...","[new, delhi, 40, year, old, businessman, died,...",
33,RANCHI: Four youths lost their lives when thei...,"[ranchi, four, youths, lost, their, lives, whe...","[ranchi, four, youths, lost, lives, car, colli...",
34,Jung Il Woo recently opened up about a pivotal...,"[jung, il, woo, recently, opened, up, about, a...","[jung, il, woo, recently, opened, pivotal, mom...",
35,PATNA: Ranjit Sah does not know the nuances of...,"[patna, ranjit, sah, does, not, know, the, nua...","[patna, ranjit, sah, know, nuances, law, provi...",
36,"Hyderabad: A 28-year-old software engineer , w...","[hyderabad, a, 28, year, old, software, engine...","[hyderabad, 28, year, old, software, engineer,...",
37,NEW DELHI: A 20-year-old woman was killed and ...,"[new, delhi, a, 20, year, old, woman, was, kil...","[new, delhi, 20, year, old, woman, killed, 62,...",

In [ ]:
print(type(news_labels['annotations'][1]))

<class 'tuple'>

In [ ]:
pprint(news_labels['annotations'][1])

('HISAR: Three men were killed and three others were injured in a car accident '
 'near a village in Hisar, according to the police. The passengers were '
 'returning to Hisar after attending a wedding ceremony in Bhiwani district on '
 'Thursday night when the driver lost control of the vehicle and crashed into '
 'a tree. The accident occurred in Harikot village. All of the individuals '
 'involved in the accident were employees of Haryana power utility, Dakshin '
 'Haryana Bijli Vitran Nigam (DHBVN). The deceased have been identified as '
 'junior engineer Bhuvnesh Sangwan from Rewari, Mandeep Kundu from Hisar, and '
 'Rajesh from Fatehabad. The injured individuals have been admitted to a '
 'hospital in Hisar. Explore Your Financial Landscape with Personalized Credit '
 'Insights.',
 {'entities': [(0, 5, 'place'),
               (95, 100, 'place'),
               (160, 165, 'place'),
               (585, 590, 'place'),
               (679, 684, 'place')]})

In [ ]:
print(type(news_labels['annotations'][1]))

<class 'tuple'>

In [ ]:
pprint(news_labels['annotations'][1])

('HISAR: Three men were killed and three others were injured in a car accident '
 'near a village in Hisar, according to the police. The passengers were '
 'returning to Hisar after attending a wedding ceremony in Bhiwani district on '
 'Thursday night when the driver lost control of the vehicle and crashed into '
 'a tree. The accident occurred in Harikot village. All of the individuals '
 'involved in the accident were employees of Haryana power utility, Dakshin '
 'Haryana Bijli Vitran Nigam (DHBVN). The deceased have been identified as '
 'junior engineer Bhuvnesh Sangwan from Rewari, Mandeep Kundu from Hisar, and '
 'Rajesh from Fatehabad. The injured individuals have been admitted to a '
 'hospital in Hisar. Explore Your Financial Landscape with Personalized Credit '
 'Insights.',
 {'entities': [(0, 5, 'place'),
               (95, 100, 'place'),
               (160, 165, 'place'),
               (585, 590, 'place'),
               (679, 684, 'place')]})

In [ ]:
news_labels.to_csv('01_03_data_annotation_for_named_entity_recognition.csv',index=False)

In [ ]:
%%capture
!pip install spacy==3.2.3

In [ ]:
import pandas as pd
import spacy
from spacy.tokens import DocBin
import ast

In [ ]:
df = pd.read_csv('/content/01_03_data_annotation_for_named_entity_recognition.csv')

In [ ]:
df['annotations'] = df['annotations'].apply(ast.literal_eval)

ValueError: malformed node or string: nan